// Mocks generated by Mockito 5.4.4 from annotations
// in book_manager/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:book_manager/application/dto/book/add_book_dto.dart' as _i5;
import 'package:book_manager/domain/book/book.dart' as _i2;
import 'package:book_manager/domain/book/book_repository_base.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBook_0 extends _i1.SmartFake implements _i2.Book {
  _FakeBook_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookRepositoryBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepositoryBase extends _i1.Mock
    implements _i3.BookRepositoryBase {
  @override
  _i4.Future<List<_i2.Book>> getBooks() => (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Book>>.value(<_i2.Book>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Book>>.value(<_i2.Book>[]),
      ) as _i4.Future<List<_i2.Book>>);

  @override
  _i4.Future<String> addBook(_i5.AddBookDto? book) => (super.noSuchMethod(
        Invocation.method(
          #addBook,
          [book],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #addBook,
            [book],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #addBook,
            [book],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateCurrentPage(
    int? bookId,
    int? currentPage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCurrentPage,
          [
            bookId,
            currentPage,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Book> getBookById(int? bookId) => (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [bookId],
        ),
        returnValue: _i4.Future<_i2.Book>.value(_FakeBook_0(
          this,
          Invocation.method(
            #getBookById,
            [bookId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Book>.value(_FakeBook_0(
          this,
          Invocation.method(
            #getBookById,
            [bookId],
          ),
        )),
      ) as _i4.Future<_i2.Book>);
}
