extend type Mutation {
  """
  ✨ Insert a single `Book` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  book_insert(
    """
    Data object to insert into the table.
    """
    data: Book_Data!
  ): Book_KeyOutput! @fdc_generated(from: "Book", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ReadingEntry` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  readingEntry_insert(
    """
    Data object to insert into the table.
    """
    data: ReadingEntry_Data!
  ): ReadingEntry_KeyOutput! @fdc_generated(from: "ReadingEntry", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Book` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  book_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Book_Data!]!
  ): [Book_KeyOutput!]! @fdc_generated(from: "Book", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ReadingEntry` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  readingEntry_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ReadingEntry_Data!]!
  ): [ReadingEntry_KeyOutput!]! @fdc_generated(from: "ReadingEntry", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Book` into the table, based on the primary key. Returns the key of the newly inserted `Book`.
  """
  book_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Book_Data!
  ): Book_KeyOutput! @fdc_generated(from: "Book", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ReadingEntry` into the table, based on the primary key. Returns the key of the newly inserted `ReadingEntry`.
  """
  readingEntry_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ReadingEntry_Data!
  ): ReadingEntry_KeyOutput! @fdc_generated(from: "ReadingEntry", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Book` objects into the table, based on the primary key. Returns the key of the newly inserted `Book`.
  """
  book_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Book_Data!]!
  ): [Book_KeyOutput!]! @fdc_generated(from: "Book", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ReadingEntry` objects into the table, based on the primary key. Returns the key of the newly inserted `ReadingEntry`.
  """
  readingEntry_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ReadingEntry_Data!]!
  ): [ReadingEntry_KeyOutput!]! @fdc_generated(from: "ReadingEntry", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Book` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  book_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Book_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Book_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Book_Data!
  ): Book_KeyOutput @fdc_generated(from: "Book", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ReadingEntry` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  readingEntry_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReadingEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReadingEntry_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ReadingEntry_Data!
  ): ReadingEntry_KeyOutput @fdc_generated(from: "ReadingEntry", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Book` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  book_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Book_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Book_Data!
  ): Int! @fdc_generated(from: "Book", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ReadingEntry` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  readingEntry_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ReadingEntry_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ReadingEntry_Data!
  ): Int! @fdc_generated(from: "ReadingEntry", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Book` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  book_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Book_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Book_FirstRow
  ): Book_KeyOutput @fdc_generated(from: "Book", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ReadingEntry` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  readingEntry_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReadingEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReadingEntry_FirstRow
  ): ReadingEntry_KeyOutput @fdc_generated(from: "ReadingEntry", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Book` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  book_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Book_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Book", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ReadingEntry` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  readingEntry_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ReadingEntry_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ReadingEntry", purpose: DELETE_MULTIPLE)
}
