extend type Book {
  """
  ✨ List `ReadingEntry` objects in a one-to-many relationship (where `ReadingEntry`.`book` is this object).
  """
  readingEntries_on_book(
    """
    Filter condition to narrow down the query results.
    """
    where: ReadingEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ReadingEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [ReadingEntry!]! @fdc_generated(from: "ReadingEntry.book", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
}
